sudo: false

language: python

python:
  - 2.7

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls

script:
  - nosetests ./specs --with-coverage

after_success:
  - coveralls
